[pytest]
# Tell pytest where the tests are
testpaths = tests

# Put a hard 3-minute limit (180 seconds) on every single test
timeout = 180

# Automatically adds the -rx flag to every pytest command 
# To list expected failures are the v1 TODO list.
addopts = -rx
